// <auto-generated />
namespace Application_crud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class emp_app1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emp_app1));
        
        string IMigrationMetadata.Id
        {
            get { return "202303081912109_emp_app1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
